### ISSUE TITLE
Add v-bind="$attrs" to video element to inherit user attributes

### ISSUE THREAD

**Issue by S-h-a-m-o-t** [AlexKratky/vue-camera-lib#4]
Hi, it would be good to add v-bind="$attrs" to video elements (of both WebCam and WebCamUI) to be able to inherit fallthrough atributes.

This is needed since your template is not a single-root-template: https://vuejs.org/guide/components/attrs.html#disabling-attribute-inheritance.

That enables to pass custom e.g. class, id attribs.

Thanks a lot.

**Comment by AlexKratky** [comment]
Fixed in 499bd6ca9e8b253bf805bde94405e6ea7d71e99c
