### ISSUE TITLE
Fix included - WebCam.vue method: start() does not set device id to first camera if no devices found

### ISSUE THREAD

**Issue by DrSpeedy** [AlexKratky/vue-camera-lib#5]
Hi, love the lib; but it does not work with some devices (like my laptop). I have traced down the issue to one line specifically in the `start()` method of `WebCam.vue` where you simply forgot to set the `this.deviceId` data point

Line 238-241
```javascript
// nothing found, use first if there is any
if ( ! this.deviceId && this.cameras.length > 0) {
    this.cameras[0].deviceId;
}
```
Specifically line 240
```javascript
this.cameras[0].deviceId;
```

Needs to be:
```javascript
this.deviceId = this.cameras[0].deviceId;
```

**Comment by AlexKratky** [comment]
Ops, you are right! I am happy to hear that you like this library and must thank you for your investigation. I fixed this in v1.0.5 and published new version to npm :)
